sudo: required
dist: trusty

before_install:
  - sudo apt-get install -y make texlive texlive-latex-extra texlive-lang-french

script:
  - make

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI"
  - git push -q https://$GITHUB_TOKEN@github.com/tomorrow-paper/paper --tags

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: paper.pdf
  on:
    branch: master